### ISSUE TITLE
Following a non-owned pawn breaks follow me until relaunch of game

### ISSUE THREAD

**Issue by MitztheKat** [FluffierThanThou/FollowMe#20]
[output_log.txt](https://github.com/FluffierThanThou/FollowMe/files/2405484/output_log.txt)
hugslib, followme
i used hugslib for a quick encounter map. from previous experience, anything not your faction will break follow me. raiders, traders, wildlife, etc.
there isn't much to say. it's as simple as that...

**Comment by MitztheKat** [comment]
give me a sec, for some reason this log is old

**Comment by MitztheKat** [comment]
[output_log.txt](https://github.com/FluffierThanThou/FollowMe/files/2405518/output_log.txt)
correct log.

**Comment by MitztheKat** [comment]
bump.
i was hoping for a response on possible replication.

**Comment by MitztheKat** [comment]
good news: whatever you did silenced the message.
Bad news: the bug is still there.
progress!

**Comment by FluffierThanThou** [comment]
@MitztheKat; sorry for the late response, I've been busy with other life and mod projects. I've run into what I assume is the same issue myself, going to have a look now. I don't remember actually making any changes - so I'm glad you've provided a log that might help a bit, since I'm also not getting any error messages.
