### ISSUE TITLE
Lag when zoom in zoom out

### ISSUE THREAD

**Issue by ghost** [FluffierThanThou/FollowMe#35]
I'm fast scrolling and see glitches, that don't see without mod

**Comment by Karel-Kroeze** [comment]
unless you have this issue _while_ follow me is active (which wouldn't make any sense, as you would then not be able to scroll), this is not really possible.

I can't do anything further without a player-log, and since it's been a year (sorry for that!), I'm going to close this for now. Feel free to reopen if this issue still exists, but please attach a player-log when you do.
